// vue/src/layout/BaseLayout.vue
<template>
  <header>This is header</header>
  <main>
    <!-- <RouterView v-slot="{ Component }">
      <KeepAlive>
        <component :is="Component" />
      </KeepAlive>
    </RouterView> -->
    <RouterView />
  </main>
  <footer>this is footer</footer>
</template>

<script setup lang="ts"></script>

// react/src/components/layout/BaseLayout.tsx
import { Suspense } from "react";
import { Outlet } from "react-router";
import NavigationProgress from "@/components/NavigationProgress";
import ErrorBoundary from "@/components/ErrorBoundary";

export default function BaseLayout() {
  return (
    <>
      <header>This is Head</header>
      <main>
        <ErrorBoundary>
          <Suspense fallback={<NavigationProgress />}>
            <Outlet />
          </Suspense>
        </ErrorBoundary>
      </main>
      <footer>This is footer</footer>
    </>
  );
}
