// vue/src/layout/BaseLayout.vue
<template>
  <header>This is header</header>
  <main>
    <!-- <RouterView v-slot="{ Component }">
      <KeepAlive>
        <component :is="Component" />
      </KeepAlive>
    </RouterView> -->
    <RouterView />
  </main>
  <footer>this is footer</footer>
</template>

<script setup lang="ts"></script>

// react/src/layout/BaseLayout.tsx
import { Suspense } from "react";
import { Outlet } from "react-router";

export default function BaseLayout() {
  return (
    <>
      <header>This is Head</header>
      <main>
        <Suspense fallback={<div>loading...</div>}>
          <Outlet />
        </Suspense>
      </main>
      <footer>This is footer</footer>
    </>
  );
}
