// react/src/views/Home.tsx
import { useCounterStore } from "@/store/counter";

export default function Home() {
  const count = useCounterStore((state) => state.count);
  const increment = useCounterStore((state) => state.increment);
  return (
    <h1 className="p-10 text-center text-3xl" onClick={increment}>
      Welcome Home, Counter is: {count}
    </h1>
  );
}

// vue/src/views/Home.vue
<template>
  <h1 class="text-center text-lg leading-8 font-bold">
    <VueIcon class="m-auto" height="50" width="50" />
    <span>{{ message }}</span>
  </h1>
  <p>Count is: {{ countStore.count }}</p>
  <button @click="countStore.increment">increment</button>
</template>

<script setup lang="ts">
  import { useCountStore } from "@/store/count";
  import VueIcon from "@/assets/icons/vue.svg?component";

  const countStore = useCountStore();
  const message = "Welcome Home";
</script>
